/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsDate } from "class-validator";
import { AppointmentUpdateManyWithoutPatientsInput } from "./AppointmentUpdateManyWithoutPatientsInput";
import { Type } from "class-transformer";
import { MedicalRecordUpdateManyWithoutPatientsInput } from "./MedicalRecordUpdateManyWithoutPatientsInput";

@InputType()
class PatientUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentUpdateManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentUpdateManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => AppointmentUpdateManyWithoutPatientsInput, {
    nullable: true,
  })
  appointments?: AppointmentUpdateManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactNumber?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => MedicalRecordUpdateManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => MedicalRecordUpdateManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => MedicalRecordUpdateManyWithoutPatientsInput, {
    nullable: true,
  })
  medicalRecords?: MedicalRecordUpdateManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;
}

export { PatientUpdateInput as PatientUpdateInput };
